#!/bin/bash

p="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

case "$1" in
    "sorry")
      aplay -q $p/paStormSounds/HAL/halsorry.wav
      ;;
    "operational")
      aplay -q $p/paStormSounds/HAL/operatnl.wav
      ;;
    "davepls")
      aplay -q $p/paStormSounds/HAL/dave.wav
      ;;
    "why")
      aplay -q $p/paStormSounds/HAL/error.wav
      ;;
    "IKNOW")
      aplay -q $p/paStormSounds/HAL/cantalow.wav
      ;;
    "results")
      cvlc --play-and-exit $p/paStormSounds/GladOS/well_done_glados.mp3
      ;;
    "-h")
      echo "one of : sorry operational davepls why IKNOW results"
      ;;
    *)
      echo "wrong command" 
      aplay -q $p/paStormSounds/HAL/halsorry.wav
      exit 1
      ;;
  esac
