#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit 1
fi

echo -e "\033[34m" ; figlet Command ; echo -e "\033[32m" ; figlet $1 ; echo -e "\033[34m" ; figlet Added ; echo -e "\033[0m"
chmod u+x $1

here="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

location=$(pwd)

if [ "$location" != "$here" ]
    then
        mv $1 "$here"
fi

# cd ~/commands
# nCommand=$(ls -p | grep -v / | wc -l)

# file=$(cowsay -l | tail -n +2 | tr ' ' '\n' | shuf -n 1)
# cowsay -f $file there is now $nCommand custom commands available !
