#!/bin/bash

if [ $# -eq 0 ]
  then
    echo "No arguments supplied"
    exit 1
fi

echo -e "\033[34m" ; figlet Command ; echo -e "\033[32m" ; figlet $1 ; echo -e "\033[34m" ; figlet Added ; echo -e "\033[0m"
chmod u+x $1

mkdir -p ~/commands

here=$(pwd)
if [ "$here" != "~/commands" ]
    then    
        mv $1 ~/commands
fi

# cd ~/commands
# nCommand=$(ls -p | grep -v / | wc -l)

# file=$(cowsay -l | tail -n +2 | tr ' ' '\n' | shuf -n 1)
# cowsay -f $file there is now $nCommand custom commands available !
